# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

silent: true

vars:
  BENCH_COUNT: 10

tasks:
  default:
    desc: "Task runner for gosynthcalc package"
    cmds:
      - echo "Task runner for gosynthcalc package. To see all of the tasks, run 'task --list'"

  test:
    desc: "Run all unit tests"
    cmds:
      - go test ./...
  
  bench-formula:
    desc: "Run chemformula benchmark"
    cmds:
      - go test -bench=BenchmarkChemicalFormula_output -count={{.BENCH_COUNT}} -run='^$' | benchstat -

  bench-reaction:
    desc: "Run chemreaction benchmark"
    cmds:
      - go test -bench=BenchmarkChemicalReaction_output -count={{.BENCH_COUNT}} -run='^$' | benchstat -
  
  bench:
    desc: "Run all benchmarks"
    cmds:
      - echo "Formula:"
      - task: bench-formula
      - echo "Reaction:"
      - task: bench-reaction
      
  prof:
    desc: "Run pprof profiler on benchmarks"
    cmds:
      - go test -bench=. -cpuprofile=cpu.pprof -memprofile=mem.pprof